# docker-compose.yml
services:
  neo4j:
    image: neo4j:5
    container_name: neo4j
    ports:
      - "7474:7474"   # Web GUI (Neo4j Browser)
      - "7687:7687"   # Bolt protocol (for drivers later)
    environment:
      NEO4J_AUTH: neo4j/password
    volumes:
      - neo4j_data:/data

volumes:
  neo4j_data:
